# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-with-front-end-new

frameworkVersion: '2'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  profile: serverless-admin
  iamRoleStatements:
    - Effect: Allow
      Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:BatchGetItem
      Resource: 'arn:aws:dynamodb:us-east-2:*:*'

# The `functions` block defines what code to deploy
functions:
  handler:
    handler: handler.handler
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: handler.handler
          method: get
          cors: true
