name: Deploy
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 12
#       - run: sudo yarn build
#       - run: yarn install --frozen-lockfile
#       - run: yarn build
      - name: Install Yarn
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
          
      - name: Build React App
        run: yarn build
